// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumNodeSlices implements CiliumNodeSliceInterface
type fakeCiliumNodeSlices struct {
	*gentype.FakeClientWithList[*v2.CiliumNodeSlice, *v2.CiliumNodeSliceList]
	Fake *FakeCiliumV2
}

func newFakeCiliumNodeSlices(fake *FakeCiliumV2) ciliumiov2.CiliumNodeSliceInterface {
	return &fakeCiliumNodeSlices{
		gentype.NewFakeClientWithList[*v2.CiliumNodeSlice, *v2.CiliumNodeSliceList](
			fake.Fake,
			"",
			v2.SchemeGroupVersion.WithResource("ciliumnodeslices"),
			v2.SchemeGroupVersion.WithKind("CiliumNodeSlice"),
			func() *v2.CiliumNodeSlice { return &v2.CiliumNodeSlice{} },
			func() *v2.CiliumNodeSliceList { return &v2.CiliumNodeSliceList{} },
			func(dst, src *v2.CiliumNodeSliceList) { dst.ListMeta = src.ListMeta },
			func(list *v2.CiliumNodeSliceList) []*v2.CiliumNodeSlice { return gentype.ToPointerSlice(list.Items) },
			func(list *v2.CiliumNodeSliceList, items []*v2.CiliumNodeSlice) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
