// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	context "context"

	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CiliumNodeSlicesGetter has a method to return a CiliumNodeSliceInterface.
// A group's client should implement this interface.
type CiliumNodeSlicesGetter interface {
	CiliumNodeSlices() CiliumNodeSliceInterface
}

// CiliumNodeSliceInterface has methods to work with CiliumNodeSlice resources.
type CiliumNodeSliceInterface interface {
	Create(ctx context.Context, ciliumNodeSlice *ciliumiov2.CiliumNodeSlice, opts v1.CreateOptions) (*ciliumiov2.CiliumNodeSlice, error)
	Update(ctx context.Context, ciliumNodeSlice *ciliumiov2.CiliumNodeSlice, opts v1.UpdateOptions) (*ciliumiov2.CiliumNodeSlice, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ciliumiov2.CiliumNodeSlice, error)
	List(ctx context.Context, opts v1.ListOptions) (*ciliumiov2.CiliumNodeSliceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ciliumiov2.CiliumNodeSlice, err error)
	CiliumNodeSliceExpansion
}

// ciliumNodeSlices implements CiliumNodeSliceInterface
type ciliumNodeSlices struct {
	*gentype.ClientWithList[*ciliumiov2.CiliumNodeSlice, *ciliumiov2.CiliumNodeSliceList]
}

// newCiliumNodeSlices returns a CiliumNodeSlices
func newCiliumNodeSlices(c *CiliumV2Client) *ciliumNodeSlices {
	return &ciliumNodeSlices{
		gentype.NewClientWithList[*ciliumiov2.CiliumNodeSlice, *ciliumiov2.CiliumNodeSliceList](
			"ciliumnodeslices",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ciliumiov2.CiliumNodeSlice { return &ciliumiov2.CiliumNodeSlice{} },
			func() *ciliumiov2.CiliumNodeSliceList { return &ciliumiov2.CiliumNodeSliceList{} },
		),
	}
}
