// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IdentityLabelsLister helps list IdentityLabelses.
// All objects returned here must be treated as read-only.
type IdentityLabelsLister interface {
	// List lists all IdentityLabelses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2alpha1.IdentityLabels, err error)
	// Get retrieves the IdentityLabels from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov2alpha1.IdentityLabels, error)
	IdentityLabelsListerExpansion
}

// identityLabelsLister implements the IdentityLabelsLister interface.
type identityLabelsLister struct {
	listers.ResourceIndexer[*ciliumiov2alpha1.IdentityLabels]
}

// NewIdentityLabelsLister returns a new IdentityLabelsLister.
func NewIdentityLabelsLister(indexer cache.Indexer) IdentityLabelsLister {
	return &identityLabelsLister{listers.New[*ciliumiov2alpha1.IdentityLabels](indexer, ciliumiov2alpha1.Resource("identitylabels"))}
}
