// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2

import (
	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumNodeSliceLister helps list CiliumNodeSlices.
// All objects returned here must be treated as read-only.
type CiliumNodeSliceLister interface {
	// List lists all CiliumNodeSlices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2.CiliumNodeSlice, err error)
	// Get retrieves the CiliumNodeSlice from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov2.CiliumNodeSlice, error)
	CiliumNodeSliceListerExpansion
}

// ciliumNodeSliceLister implements the CiliumNodeSliceLister interface.
type ciliumNodeSliceLister struct {
	listers.ResourceIndexer[*ciliumiov2.CiliumNodeSlice]
}

// NewCiliumNodeSliceLister returns a new CiliumNodeSliceLister.
func NewCiliumNodeSliceLister(indexer cache.Indexer) CiliumNodeSliceLister {
	return &ciliumNodeSliceLister{listers.New[*ciliumiov2.CiliumNodeSlice](indexer, ciliumiov2.Resource("ciliumnodeslice"))}
}
